const sidebar = [
  {
    text: 'Quick Start',
    // collapsible: true,
    items: [
      // { text: 'Installation', link: '/docs/installation' },
      { text: '<i class="si si-terminal"></i>Leaf CLI', link: '/docs/cli/' },
      {
        text: '<i class="si si-sparkles"></i>AI in Leaf <span class="badge new">New</span>',
        link: '/docs/ai',
      },
      {
        text: '<i class="si si-zap"></i>Why Leaf 5 <span class="badge new">New</span>',
        link: '/docs/why-leaf-5',
      },
      {
        text: '<i class="si si-arrow-up"></i>Upgrading to Leaf 5 <span class="badge new">New</span>',
        link: '/docs/upgrade-guide',
      },
      // { text: 'Functional Mode', link: '/docs/config/functional-mode' },
      { text: '<i class="si si-package"></i>Modules', link: '/docs/modules' },
      { text: '<i class="si si-layout"></i>App Scaffolding', link: '/docs/mvc/scaffolds' },
    ],
  },
  // {
  //   text: 'Leaf CLI',
  //   // collapsible: true,
  //   // collapsed: true,
  //   items: [
  //     { text: 'Creating apps', link: '/docs/cli/creating-an-app' },
  //     { text: 'Managing apps', link: '/docs/cli/managing-apps' },
  //   ],
  // },
  {
    text: 'Routing',
    // collapsible: true,
    items: [
      { text: '<i class="si si-route"></i>Basic Routing', link: '/docs/routing/' },
      { text: '<i class="si si-layers"></i>Route Groups', link: '/docs/routing/route-groups' },
      { text: '<i class="si si-shuffle"></i>Dynamic routing', link: '/docs/routing/dynamic' },
      { text: '<i class="si si-filter"></i>Middleware', link: '/docs/routing/middleware/' },
      // { text: 'Middleware in Leaf MVC', link: '/docs/routing/middleware/mvc' },
    ],
  },
  {
    text: 'Request/Response',
    // collapsible: true,
    items: [
      { text: '<i class="si si-inbox"></i>Request', link: '/docs/http/request' },
      { text: '<i class="si si-send"></i>Response', link: '/docs/http/response' },
      { text: '<i class="si si-list"></i>Headers', link: '/docs/http/headers' },
      { text: '<i class="si si-globe"></i>CORS', link: '/docs/http/cors' },
    ],
  },
  {
    text: 'Config & Deployment',
    // collapsible: true,
    items: [
      // { text: 'Overview', link: '/docs/config/' },
      // { text: 'App settings', link: '/docs/config/settings' },
      { text: '<i class="si si-sliders"></i>Application Env', link: '/docs/config/environment' },
      { text: '<i class="si si-rocket"></i>Deployment', link: '/learn/deployment/' },
      { text: '<i class="si si-alert"></i>Error Handling', link: '/docs/routing/error-handling' },
      { text: '<i class="si si-box"></i>Dependency Injection', link: '/docs/config/container' },
      // { text: 'Logging', link: '/docs/utils/logging' },
      { text: '<i class="si si-gauge"></i>Async PHP (Swoole/ReactPHP)', link: '/docs/swoole' },
      { text: '<i class="si si-container"></i>Using Docker', link: '/docs/docker' },
      // { text: '<i class="si si-alert"></i>Debugging', link: '/docs/routing/error-handling' },
      // { text: 'Leaf Devtools', link: '/docs/utils/devtools' },
      // { text: 'Deployment', link: '/docs/config/deployment' },
      {
        text: '<i class="si si-flask"></i>Testing & Code Quality <span class="badge new">New</span>',
        link: '/docs/utils/testing',
      },
    ],
  },
  {
    text: 'Database',
    // collapsible: true,
    items: [
      { text: '<i class="si si-database"></i>Introduction', link: '/docs/database/' },
      // { text: 'MVC Support', link: '/docs/database/mvc' },
      { text: '<i class="si si-wrench"></i>Query Builder', link: '/docs/database/builder' },
      { text: '<i class="si si-server"></i>Leaf Redis', link: '/docs/database/redis' },
      // { text: 'Other DB Engines', link: '/docs/database/other' },
    ],
  },
  {
    text: 'Authentication',
    // collapsible: true,
    items: [
      { text: '<i class="si si-shield"></i>Introduction', link: '/docs/auth/' },
      // { text: 'MVC Support', link: '/docs/auth/mvc' },
      // { text: 'Auth Config', link: '/docs/auth/config' },
      { text: '<i class="si si-log-in"></i>User Login', link: '/docs/auth/login' },
      { text: '<i class="si si-user-plus"></i>User Sign Up', link: '/docs/auth/signup' },
      { text: '<i class="si si-user"></i>Auth User', link: '/docs/auth/user' },
      {
        text: '<i class="si si-lock"></i>Protecting your routes',
        link: '/docs/auth/protected-routes',
      },
      { text: '<i class="si si-key"></i>Roles/Permissions', link: '/docs/auth/permissions' },
      // { text: 'Build your own auth library', link: '/docs/auth/helpers' },
    ],
  },
  {
    text: 'Sessions',
    // collapsible: true,
    items: [
      { text: '<i class="si si-clock"></i>Using Sessions', link: '/docs/http/session' },
      { text: '<i class="si si-zap"></i>Session Flash', link: '/docs/http/flash' },
      { text: '<i class="si si-cookie"></i>Cookies', link: '/docs/http/cookies' },
    ],
  },
  {
    text: 'Security',
    // collapsible: true,
    items: [
      { text: '<i class="si si-check"></i>Validation', link: '/docs/data/validation' },
      { text: '<i class="si si-shield"></i>CSRF Protection', link: '/docs/security/csrf' },
      { text: '<i class="si si-key"></i>Leaf Password', link: '/docs/data/encryption' },
      { text: '<i class="si si-lock"></i>General Security', link: '/docs/security/anchor' },
    ],
  },
  {
    text: 'Utilities',
    // collapsible: true,
    items: [
      { text: '<i class="si si-calendar"></i>Date/Time', link: '/docs/utils/date' },
      { text: '<i class="si si-download"></i>Data Fetching', link: '/docs/utils/fetch' },
      { text: '<i class="si si-clock"></i>HTTP Cache', link: '/docs/http/caching' },
      { text: '<i class="si si-mail"></i>Leaf Mail', link: '/docs/utils/mail/' },
      { text: '<i class="si si-card"></i>Leaf Billing', link: '/docs/utils/billing' },
      { text: '<i class="si si-archive"></i>Caching', link: '/docs/utils/cache' },
      { text: '<i class="si si-folder"></i>File System', link: '/docs/utils/fs' },
      { text: '<i class="si si-layers"></i>Queues/Jobs', link: '/docs/utils/queues' },
      { text: '<i class="si si-globe"></i>Multi-Language', link: '/docs/utils/lingo' },
      { text: '<i class="si si-map"></i>Sitemaps', link: '/docs/utils/sitemaps' },
    ],
  },
  {
    text: 'Frontend',
    // collapsible: true,
    items: [
      { text: '<i class="si si-monitor"></i>Introduction', link: '/docs/frontend/' },
      { text: '<i class="si si-file-code"></i>Leaf Blade', link: '/docs/frontend/blade' },
      { text: '<i class="si si-atom"></i>Inertia JS', link: '/docs/frontend/inertia' },
      { text: '<i class="si si-zap"></i>Vite JS', link: '/docs/frontend/vite' },
      { text: '<i class="si si-wind"></i>Tailwind CSS', link: '/docs/frontend/tailwind' },
      { text: '<i class="si si-layout"></i>Bare UI', link: '/docs/frontend/bareui' },
      { text: '<i class="si si-puzzle"></i>Other Engines', link: '/docs/frontend/third-party' },
      // { text: 'Leaf UI', link: '/docs/frontend/leaf-ui' },
      // {
      //   text: 'Leaf Zero',
      //   collapsible: true,
      //   collapsed: true,
      //   items: [
      //     { text: 'Introduction', link: '/docs/frontend/zero/' },
      //     // { text: 'Layouts', link: '/docs/frontend/zero/layouts' },
      //     { text: 'Forms', link: '/docs/frontend/zero/forms' },
      //     // { text: 'Modals', link: '/docs/frontend/zero/modals' },
      //     // { text: 'Alerts', link: '/docs/frontend/zero/alerts' },
      //     // { text: 'Loading', link: '/docs/frontend/zero/loading' },
      //     { text: 'Icons', link: '/docs/frontend/zero/icons' },
      //     // { text: 'Forms', link: '/docs/frontend/zero/forms' },
      //     { text: 'Merketing Sections', link: '/docs/frontend/zero/marketing' },
      //     // { text: 'Dashboard Sections', link: '/docs/frontend/zero/dashboard' },
      //   ],
      // },
    ],
  },
  {
    text: 'Building to scale',
    // collapsible: true,
    items: [
      // { text: 'Leaf + MVC', link: '/docs/mvc/' },
      // { text: 'Leaf MVC v4', link: '/docs/mvc/mvc4' },
      { text: '<i class="si si-git-branch"></i>Controllers', link: '/docs/mvc/controllers' },
      // { text: 'Views', link: '/docs/frontend/mvc' },
      { text: '<i class="si si-database"></i>Models', link: '/docs/database/models' },
      // { text: 'Migrations', link: '/docs/database/migrations' },
      // { text: 'JSON Schema', link: '/docs/database/schema' },
      { text: '<i class="si si-file-text"></i>Schema Files', link: '/docs/database/files' },
      { text: '<i class="si si-briefcase"></i>Services', link: '/docs/mvc/services' },
      // { text: 'Factories', link: '/docs/database/factories' },
      // { text: 'Mailing', link: '/docs/utils/mail/mvc' },
      { text: '<i class="si si-globe"></i>MVC Globals', link: '/docs/mvc/globals' },
      { text: '<i class="si si-book"></i>Custom Libraries', link: '/docs/mvc/libraries' },
      // { text: 'MVC Console Tool', link: '/docs/mvc/console' },
    ],
  },
  {
    text: 'Console Apps',
    // collapsible: true,
    items: [
      { text: '<i class="si si-sprout"></i>Leaf Seedling', link: '/docs/seedling/' },
      { text: '<i class="si si-terminal"></i>Writing Commands', link: '/docs/mvc/commands' },
    ],
  },
  // {
  //   text: 'Codelabs',
  //   // collapsible: true,
  //   // collapsed: true,
  //   items: [
  //     { text: 'Intro', link: '/codelabs/' },
  //     { text: 'Contributing', link: '/codelabs/contributing' },
  //     // { text: '<i class="si si-rocket"></i>Deployment', link: '/learn/deployment/' },
  //     // { text: 'Authentication', link: '/learn/auth/' },
  //   ],
  // },
];

export default sidebar;
