const sidebar = [
  {
    text: 'Quick Start',
    // collapsible: true,
    // collapsed: true,
    items: [
      // { text: 'Installation', link: '/docs/installation' },
      { text: 'Leaf CLI', link: '/docs/cli/' },
      { text: 'Migration Guide', link: '/docs/migrating' },
      // { text: 'Functional Mode', link: '/docs/config/functional-mode' },
      { text: 'Modules', link: '/docs/modules' },
      { text: 'Leaf MVC Scaffolding', link: '/docs/mvc/scaffolds' },
    ],
  },
  // {
  //   text: 'Leaf CLI',
  //   // collapsible: true,
  //   // collapsed: true,
  //   items: [
  //     { text: 'Creating apps', link: '/docs/cli/creating-an-app' },
  //     { text: 'Managing apps', link: '/docs/cli/managing-apps' },
  //   ],
  // },
  {
    text: 'Routing',
    // collapsible: true,
    // collapsed: true,
    items: [
      { text: 'Basic Routing', link: '/docs/routing/' },
      { text: 'Route Groups', link: '/docs/routing/route-groups' },
      { text: 'Dynamic routing', link: '/docs/routing/dynamic' },
      { text: 'Middleware', link: '/docs/routing/middleware/' },
      // { text: 'Middleware in Leaf MVC', link: '/docs/routing/middleware/mvc' },
    ],
  },
  {
    text: 'Request/Response',
    // collapsible: true,
    // collapsed: true,
    items: [
      { text: 'Request', link: '/docs/http/request' },
      { text: 'Response', link: '/docs/http/response' },
      { text: 'Headers', link: '/docs/http/headers' },
      { text: 'CORS', link: '/docs/http/cors' },
    ],
  },
  {
    text: 'Config & Deployment',
    // collapsible: true,
    // collapsed: true,
    items: [
      // { text: 'Overview', link: '/docs/config/' },
      // { text: 'App settings', link: '/docs/config/settings' },
      { text: 'Application Env', link: '/docs/config/environment' },
      { text: 'Deployment', link: '/learn/deployment/' },
      { text: 'Error Handling', link: '/docs/routing/error-handling' },
      { text: 'Dependency Injection', link: '/docs/config/container' },
      // { text: 'Logging', link: '/docs/utils/logging' },
      { text: 'Using Swoole', link: '/docs/swoole' },
      { text: 'Using Docker', link: '/docs/docker' },
      { text: 'Debugging', link: '/docs/config/debugging' },
      // { text: 'Leaf Devtools', link: '/docs/utils/devtools' },
      // { text: 'Deployment', link: '/docs/config/deployment' },
      { text: 'Testing/Linting', link: '/docs/utils/testing' },
    ],
  },
  {
    text: 'Database',
    // collapsible: true,
    // collapsed: true,
    items: [
      { text: 'Introduction', link: '/docs/database/' },
      // { text: 'MVC Support', link: '/docs/database/mvc' },
      { text: 'Query Builder', link: '/docs/database/builder' },
      { text: 'Leaf Redis', link: '/docs/database/redis' },
      // { text: 'Other DB Engines', link: '/docs/database/other' },
    ],
  },
  {
    text: 'Authentication',
    // collapsible: true,
    // collapsed: true,
    items: [
      { text: 'Introduction', link: '/docs/auth/' },
      // { text: 'MVC Support', link: '/docs/auth/mvc' },
      // { text: 'Auth Config', link: '/docs/auth/config' },
      { text: 'User Login', link: '/docs/auth/login' },
      { text: 'User Sign Up', link: '/docs/auth/signup' },
      { text: 'Auth User', link: '/docs/auth/user' },
      {
        text: 'Protecting your routes',
        link: '/docs/auth/protected-routes',
      },
      { text: 'Roles/Permissions', link: '/docs/auth/permissions' },
      // { text: 'Build your own auth library', link: '/docs/auth/helpers' },
    ],
  },
  {
    text: 'Sessions',
    // collapsible: true,
    // collapsed: true,
    items: [
      { text: 'Using Sessions', link: '/docs/http/session' },
      { text: 'Session Flash', link: '/docs/http/flash' },
      { text: 'Cookies', link: '/docs/http/cookies' },
    ],
  },
  {
    text: 'Security',
    // collapsible: true,
    // collapsed: true,
    items: [
      { text: 'Validation', link: '/docs/data/validation' },
      { text: 'CSRF Protection', link: '/docs/security/csrf' },
      { text: 'Leaf Password', link: '/docs/data/encryption' },
      { text: 'General Security', link: '/docs/security/anchor' },
    ],
  },
  {
    text: 'Utilities',
    // collapsible: true,
    // collapsed: true,
    items: [
      { text: 'Date/Time', link: '/docs/utils/date' },
      { text: 'Data Fetching', link: '/docs/utils/fetch' },
      { text: 'HTTP Cache', link: '/docs/http/caching' },
      { text: 'Leaf Mail', link: '/docs/utils/mail/' },
      { text: 'File System', link: '/docs/utils/fs' },
      { text: 'Queues/Jobs', link: '/docs/utils/queues' },
    ],
  },
  {
    text: 'Frontend',
    // collapsible: true,
    // collapsed: true,
    items: [
      { text: 'Introduction', link: '/docs/frontend/' },
      { text: 'Bare UI', link: '/docs/frontend/bareui' },
      { text: 'Leaf Blade', link: '/docs/frontend/blade' },
      { text: 'Other Engines', link: '/docs/frontend/third-party' },
      { text: 'Vite JS', link: '/docs/frontend/vite' },
      { text: 'Tailwind CSS', link: '/docs/frontend/tailwind' },
      { text: 'Inertia JS', link: '/docs/frontend/inertia' },
      // { text: 'Leaf UI', link: '/docs/frontend/leaf-ui' },
      // {
      //   text: 'Leaf Zero',
      //   collapsible: true,
      //   collapsed: true,
      //   items: [
      //     { text: 'Introduction', link: '/docs/frontend/zero/' },
      //     { text: 'Layouts', link: '/docs/frontend/zero/layouts' },
      //     { text: 'Forms', link: '/docs/frontend/zero/forms' },
      //     { text: 'Modals', link: '/docs/frontend/zero/modals' },
      //     { text: 'Alerts', link: '/docs/frontend/zero/alerts' },
      //     { text: 'Loading', link: '/docs/frontend/zero/loading' },
      //     { text: 'Icons', link: '/docs/frontend/zero/icons' },
      //     { text: 'Forms', link: '/docs/frontend/zero/forms' },
      //     { text: 'Merketing Sections', link: '/docs/frontend/zero/marketing' },
      //     { text: 'Dashboard Sections', link: '/docs/frontend/zero/dashboard' },
      //   ],
      // },
    ],
  },
  {
    text: 'Building to scale',
    // collapsible: true,
    // collapsed: true,
    items: [
      // { text: 'Leaf + MVC', link: '/docs/mvc/' },
      // { text: 'Leaf MVC v4', link: '/docs/mvc/mvc4' },
      { text: 'Controllers', link: '/docs/mvc/controllers' },
      // { text: 'Views', link: '/docs/frontend/mvc' },
      { text: 'Models', link: '/docs/database/models' },
      // { text: 'Migrations', link: '/docs/database/migrations' },
      // { text: 'JSON Schema', link: '/docs/database/schema' },
      { text: 'Schema Files', link: '/docs/database/files' },
      // { text: 'Seeders', link: '/docs/database/seeders' },
      // { text: 'Factories', link: '/docs/database/factories' },
      { text: 'Writing Commands', link: '/docs/mvc/commands' },
      // { text: 'Mailing', link: '/docs/utils/mail/mvc' },
      { text: 'MVC Globals', link: '/docs/mvc/globals' },
      { text: 'Custom Libraries', link: '/docs/mvc/libraries' },
      { text: 'MVC Console Tool', link: '/docs/mvc/console' },
    ],
  },
  // {
  //   text: 'Codelabs',
  //   // collapsible: true,
  //   // collapsed: true,
  //   items: [
  //     { text: 'Intro', link: '/codelabs/' },
  //     { text: 'Contributing', link: '/codelabs/contributing' },
  //     // { text: 'Deployment', link: '/learn/deployment/' },
  //     // { text: 'Authentication', link: '/learn/auth/' },
  //   ],
  // },
];

export default sidebar;
